apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-pvc
  labels:
    app: broker
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi